PRAGMA foreign_keys = ON;


drop table if exists Student;
drop table if exists Exam;

CREATE TABLE Student (
id_student INTEGER PRIMARY KEY,
name VARCHAR NOT NULL
);


CREATE TABLE Exam (
id_exam INTEGER PRIMARY KEY,
name VARCHAR NOT NULL,
year INTEGER NOT NULL
);


INSERT INTO Student VALUES(1,'Cat');
INSERT INTO Student VALUES(2,'Ines');
INSERT INTO Student VALUES(3,'Mario');

INSERT INTO Exam VALUES(1,'IART',3);
INSERT INTO Exam VALUES(2,'PLOG',3);
INSERT INTO Exam VALUES(3,'CAL',2);
INSERT INTO Exam VALUES(4,'AEDA',2);
INSERT INTO Exam VALUES(5,'LDSO',4);
INSERT INTO Exam VALUES(6,'PROG',1);
INSERT INTO Exam VALUES(7,'AAAA',5);
INSERT INTO Exam VALUES(8,'BBBB',1);