//
// Created by gomes on 23/03/2017.
//

#ifndef EXAMSCHEDULER_UTILS_H
#define EXAMSCHEDULER_UTILS_H

#define HOURS_PER_DAY 8;
#define REPETITIONS 40;
#define NUM_ELITISTS 3;
#define CROSSING_PROB 90;
#define MUTATION_PROB 15;

#endif //EXAMSCHEDULER_UTILS_H
